import './globals.css';
import { Inter } from 'next/font/google';
import NavBar from './(components)/NavBar';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';

config.autoAddCss = false;
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Ticket App',
	description: 'Generated by Yogesh Ganesh',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='flex flex-col h-screen max-h-screen'>
					<NavBar />
					<div className='flex-grow overflow-y-auto bg-cyan-950'>
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
